persuasion_techniques_1 = {
    'Level 1': ['Persuasion'],
    'Level 2': ['Ethos', 'Pathos', 'Logos'],
    'Level 3': [
        'Ad Hominem', 'Bandwagon', 'Appeal to authority', 'Glittering generalities (Virtue)',
        'Exaggeration/Minimisation', 'Loaded Language', 'Flag-waving',
        'Appeal to fear/prejudice', 'Repetition', 'Obfuscation, Intentional vagueness, Confusion',
        'Justification', 'Reasoning'
        ],

    'Level 4': ['Slogans', 'Bandwagon', 'Appeal to authority', 'Flag-waving', 'Appeal to fear/prejudice',
                'Name calling/Labeling', 'Doubt', 'Smears', 'Reductio ad hitlerum', 'Distraction',
                'Simplification', 'Whataboutism'],

    'Level 5': ["Misrepresentation of Someone's Position (Straw Man)", 'Causal Oversimplification',
                'Black-and-white Fallacy/Dictatorship', 'Thought-terminating cliché',
                'Presenting Irrelevant Data (Red Herring)', 'Whataboutism']
    }

techniques_to_level_1 = {
    'Persuasion': ['Level 1'],
    'Ethos': ['Level 2'],
    'Pathos': ['Level 2'],
    'Logos': ['Level 2'],
    'Ad Hominem': ['Level 3'],
    'Bandwagon': ['Level 3', 'Level 4'],
    'Appeal to authority': ['Level 3', 'Level 4'],
    'Glittering generalities (Virtue)': ['Level 3'],
    'Exaggeration/Minimisation': ['Level 3'],
    'Loaded Language': ['Level 3'],
    'Flag-waving': ['Level 3', 'Level 4'],
    'Appeal to fear/prejudice': ['Level 3', 'Level 4'],
    'Repetition': ['Level 3'],
    'Obfuscation, Intentional vagueness, Confusion': ['Level 3'],
    'Justification': ['Level 3'],
    'Reasoning': ['Level 3'],
    'Slogans': ['Level 4'],
    'Name calling/Labeling': ['Level 4'],
    'Doubt': ['Level 4'],
    'Smears': ['Level 4'],
    'Reductio ad hitlerum': ['Level 4'],
    'Distraction': ['Level 4'],
    'Simplification': ['Level 4'],
    'Whataboutism': ['Level 4', 'Level 5'],
    "Misrepresentation of Someone's Position (Straw Man)": ['Level 5'],
    'Causal Oversimplification': ['Level 5'],
    'Black-and-white Fallacy/Dictatorship': ['Level 5'],
    'Thought-terminating cliché': ['Level 5'],
    'Presenting Irrelevant Data (Red Herring)': ['Level 5']}

hierarchy_1 = {
    'Level 1': {
        'Pathos': ['Persuasion'],
        'Logos': ['Persuasion'],
        'Ethos': ['Persuasion'],
        'None': ['None']},
    'Level 2': {
        'Ad Hominem': ['Ethos'],
        'Bandwagon': ['Ethos'],
        'Appeal to authority': ['Ethos'],
        'Glittering generalities (Virtue)': ['Ethos'],
        'Exaggeration/Minimisation': ['Pathos'],
        'Loaded Language': ['Pathos'],
        'Flag-waving': ['Pathos'],
        'Appeal to fear/prejudice': ['Pathos'],
        'Justification': ['Logos'],
        'Reasoning': ['Logos'],
        'Repetition': ['Logos'],
        'Obfuscation, Intentional vagueness, Confusion': ['Logos'],
        'None': ['None']},
    'Level 3': {
        'Name calling/Labeling': ['Ad Hominem'],
        'Doubt': ['Ad Hominem'],
        'Smears': ['Ad Hominem'],
        'Reductio ad hitlerum': ['Ad Hominem'],
        'Whataboutism': ['Ad Hominem'],
        'Slogans': ['Justification'],
        'Bandwagon': ['Justification'],
        'Appeal to authority': ['Justification'],
        'Flag-waving': ['Justification'],
        'Appeal to fear/prejudice': ['Justification'],
        'Simplification': ['Reasoning'],
        'Distraction': ['Reasoning'],
        'None': ['None', 'Bandwagon', 'Appeal to authority', 'Glittering generalities (Virtue)',
                 'Exaggeration/Minimisation', 'Loaded Language', 'Flag-waving', 'Appeal to fear/prejudice',
                 'Appeal to fear/prejudice', 'Repetition',
                 'Obfuscation, Intentional vagueness, Confusion']},
    'Level 4': {
        'Causal Oversimplification': ['Simplification'],
        'Black-and-white Fallacy/Dictatorship': ['Simplification'],
        'Thought-terminating cliché': ['Simplification'],
        "Misrepresentation of Someone's Position (Straw Man)": ['Distraction'],
        'Presenting Irrelevant Data (Red Herring)': ['Distraction'],
        'Whataboutism': ['Distraction'],
        'None': ['None', 'Name calling/Labeling', 'Doubt', 'Smears', 'Reductio ad hitlerum',
                 'Whataboutism', 'Slogans', 'Bandwagon', 'Appeal to authority', 'Flag-waving',
                 'Appeal to fear/prejudice']}
    }

indexed_persuasion_techniques_1 = {
    'Level 1': {'Persuasion': 0},
    'Level 2': {'Ethos': 0, 'Pathos': 1, 'Logos': 2},
    'Level 3': {
        'Ad Hominem': 0,
        'Bandwagon': 1,
        'Appeal to authority': 2,
        'Glittering generalities (Virtue)': 3,
        'Exaggeration/Minimisation': 4,
        'Loaded Language': 5,
        'Flag-waving': 6,
        'Appeal to fear/prejudice': 7,
        'Repetition': 8,
        'Obfuscation, Intentional vagueness, Confusion': 9,
        'Justification': 10,
        'Reasoning': 11},
    'Level 4': {
        'Slogans': 0,
        'Bandwagon': 1,
        'Appeal to authority': 2,
        'Flag-waving': 3,
        'Appeal to fear/prejudice': 4,
        'Name calling/Labeling': 5,
        'Doubt': 6,
        'Smears': 7,
        'Reductio ad hitlerum': 8,
        'Distraction': 9,
        'Simplification': 10,
        'Whataboutism': 11},
    'Level 5': {
        "Misrepresentation of Someone's Position (Straw Man)": 0,
        'Causal Oversimplification': 1,
        'Black-and-white Fallacy/Dictatorship': 2,
        'Thought-terminating cliché': 3,
        'Presenting Irrelevant Data (Red Herring)': 4,
        'Whataboutism': 5}
    }

id2label_1 = {
    'Level 1': {0: 'Persuasion', 1: 'None'},
    'Level 2': {0: 'Ethos', 1: 'Pathos', 2: 'Logos', 3: 'None'},
    'Level 3': {
        0: 'Ad Hominem',
        1: 'Bandwagon',
        2: 'Appeal to authority',
        3: 'Glittering generalities (Virtue)',
        4: 'Exaggeration/Minimisation',
        5: 'Loaded Language',
        6: 'Flag-waving',
        7: 'Appeal to fear/prejudice',
        8: 'Repetition',
        9: 'Obfuscation, Intentional vagueness, Confusion',
        10: 'Justification',
        11: 'Reasoning',
        12: 'None'},
    'Level 4': {
        0: 'Slogans',
        1: 'Bandwagon',
        2: 'Appeal to authority',
        3: 'Flag-waving',
        4: 'Appeal to fear/prejudice',
        5: 'Name calling/Labeling',
        6: 'Doubt',
        7: 'Smears',
        8: 'Reductio ad hitlerum',
        9: 'Distraction',
        10: 'Simplification',
        11: 'Whataboutism',
        12: 'None'},
    'Level 5': {
        0: "Misrepresentation of Someone's Position (Straw Man)",
        1: 'Causal Oversimplification',
        2: 'Black-and-white Fallacy/Dictatorship',
        3: 'Thought-terminating cliché',
        4: 'Presenting Irrelevant Data (Red Herring)',
        5: 'Whataboutism',
        6: 'None'}}

id2leaf_label = {
    'Level 3': {
        1: 'Bandwagon',
        2: 'Appeal to authority',
        3: 'Glittering generalities (Virtue)',
        4: 'Exaggeration/Minimisation',
        5: 'Loaded Language',
        6: 'Flag-waving',
        7: 'Appeal to fear/prejudice',
        8: 'Repetition',
        9: 'Obfuscation, Intentional vagueness, Confusion', },

    'Level 4': {
        0: 'Slogans',
        1: 'Bandwagon',
        2: 'Appeal to authority',
        3: 'Flag-waving',
        4: 'Appeal to fear/prejudice',
        5: 'Name calling/Labeling',
        6: 'Doubt',
        7: 'Smears',
        8: 'Reductio ad hitlerum',
        11: 'Whataboutism'},

    'Level 5': {
        0: "Misrepresentation of Someone's Position (Straw Man)",
        1: 'Causal Oversimplification',
        2: 'Black-and-white Fallacy/Dictatorship',
        3: 'Thought-terminating cliché',
        4: 'Presenting Irrelevant Data (Red Herring)',
        5: 'Whataboutism'}}

persuasion_techniques_2a = {
    'Level 1': ['Persuasion'],
    'Level 2': ['Ethos', 'Pathos', 'Logos'],
    'Level 3': [
        'Ad Hominem', 'Bandwagon', 'Appeal to authority', 'Glittering generalities (Virtue)',
        'Exaggeration/Minimisation', 'Loaded Language', 'Flag-waving', 'Appeal to (Strong) Emotions',
        'Appeal to fear/prejudice', 'Repetition', 'Obfuscation, Intentional vagueness, Confusion',
        'Justification', 'Reasoning', 'Transfer'
        ],

    'Level 4': ['Slogans', 'Bandwagon', 'Appeal to authority', 'Flag-waving', 'Appeal to fear/prejudice',
                'Name calling/Labeling', 'Doubt', 'Smears', 'Reductio ad hitlerum', 'Distraction',
                'Simplification', 'Whataboutism'],

    'Level 5': ["Misrepresentation of Someone's Position (Straw Man)", 'Causal Oversimplification',
                'Black-and-white Fallacy/Dictatorship', 'Thought-terminating cliché',
                'Presenting Irrelevant Data (Red Herring)', 'Whataboutism']
    }

hierarchy_subtask_2a = {
    'Level 1': {
        'Pathos': ['Persuasion'],
        'Logos': ['Persuasion'],
        'Ethos': ['Persuasion'],
        'None': ['None']},
    'Level 2': {
        'Ad Hominem': ['Ethos'],
        'Bandwagon': ['Ethos'],
        'Appeal to authority': ['Ethos'],
        'Glittering generalities (Virtue)': ['Ethos'],
        'Exaggeration/Minimisation': ['Pathos'],
        'Loaded Language': ['Pathos'],
        'Flag-waving': ['Pathos'],
        'Appeal to fear/prejudice': ['Pathos'],
        'Transfer': ['Pathos', 'Ethos'],
        'Appeal to (Strong) Emotions': ['Pathos'],
        'Justification': ['Logos'],
        'Reasoning': ['Logos'],
        'Repetition': ['Logos'],
        'Obfuscation, Intentional vagueness, Confusion': ['Logos'],
        'None': ['None']},
    'Level 3': {
        'Name calling/Labeling': ['Ad Hominem'],
        'Doubt': ['Ad Hominem'],
        'Smears': ['Ad Hominem'],
        'Reductio ad hitlerum': ['Ad Hominem'],
        'Whataboutism': ['Ad Hominem'],
        'Slogans': ['Justification'],
        'Bandwagon': ['Justification'],
        'Appeal to authority': ['Justification'],
        'Flag-waving': ['Justification'],
        'Appeal to fear/prejudice': ['Justification'],
        'Simplification': ['Reasoning'],
        'Distraction': ['Reasoning'],
        'None': ['None', 'Bandwagon', 'Appeal to authority', 'Glittering generalities (Virtue)',
                 'Exaggeration/Minimisation', 'Loaded Language', 'Flag-waving', 'Appeal to fear/prejudice',
                 'Appeal to fear/prejudice', 'Transfer', 'Repetition', 'Appeal to (Strong) Emotions',
                 'Obfuscation, Intentional vagueness, Confusion']},
    'Level 4': {
        'Causal Oversimplification': ['Simplification'],
        'Black-and-white Fallacy/Dictatorship': ['Simplification'],
        'Thought-terminating cliché': ['Simplification'],
        "Misrepresentation of Someone's Position (Straw Man)": ['Distraction'],
        'Presenting Irrelevant Data (Red Herring)': ['Distraction'],
        'Whataboutism': ['Distraction'],
        'None': ['None', 'Name calling/Labeling', 'Doubt', 'Smears', 'Reductio ad hitlerum',
                 'Whataboutism', 'Slogans', 'Bandwagon', 'Appeal to authority', 'Flag-waving',
                 'Appeal to fear/prejudice']}
    }

indexed_persuasion_techniques_2a = {
    'Level 1': {'Persuasion': 0},
    'Level 2': {'Ethos': 0, 'Pathos': 1, 'Logos': 2},
    'Level 3': {
        'Ad Hominem': 0,
        'Bandwagon': 1,
        'Appeal to authority': 2,
        'Glittering generalities (Virtue)': 3,
        'Exaggeration/Minimisation': 4,
        'Loaded Language': 5,
        'Flag-waving': 6,
        'Appeal to (Strong) Emotions': 7,
        'Appeal to fear/prejudice': 8,
        'Repetition': 9,
        'Obfuscation, Intentional vagueness, Confusion': 10,
        'Justification': 11,
        'Reasoning': 12,
        'Transfer': 13},
    'Level 4': {
        'Slogans': 0,
        'Bandwagon': 1,
        'Appeal to authority': 2,
        'Flag-waving': 3,
        'Appeal to fear/prejudice': 4,
        'Name calling/Labeling': 5,
        'Doubt': 6,
        'Smears': 7,
        'Reductio ad hitlerum': 8,
        'Distraction': 9,
        'Simplification': 10,
        'Whataboutism': 11},
    'Level 5': {
        "Misrepresentation of Someone's Position (Straw Man)": 0,
        'Causal Oversimplification': 1,
        'Black-and-white Fallacy/Dictatorship': 2,
        'Thought-terminating cliché': 3,
        'Presenting Irrelevant Data (Red Herring)': 4,
        'Whataboutism': 5}}

id2label_subtask_2a = {
    'Level 1': {0: 'Persuasion', 1: 'None'},
    'Level 2': {0: 'Ethos', 1: 'Pathos', 2: 'Logos', 3: 'None'},
    'Level 3': {
        0: 'Ad Hominem',
        1: 'Bandwagon',
        2: 'Appeal to authority',
        3: 'Glittering generalities (Virtue)',
        4: 'Exaggeration/Minimisation',
        5: 'Loaded Language',
        6: 'Flag-waving',
        7: 'Appeal to (Strong) Emotions',
        8: 'Appeal to fear/prejudice',
        9: 'Repetition',
        10: 'Obfuscation, Intentional vagueness, Confusion',
        11: 'Justification',
        12: 'Reasoning',
        13: 'Transfer',
        14: 'None'},
    'Level 4': {
        0: 'Slogans',
        1: 'Bandwagon',
        2: 'Appeal to authority',
        3: 'Flag-waving',
        4: 'Appeal to fear/prejudice',
        5: 'Name calling/Labeling',
        6: 'Doubt',
        7: 'Smears',
        8: 'Reductio ad hitlerum',
        9: 'Distraction',
        10: 'Simplification',
        11: 'Whataboutism',
        12: 'None'},
    'Level 5': {
        0: "Misrepresentation of Someone's Position (Straw Man)",
        1: 'Causal Oversimplification',
        2: 'Black-and-white Fallacy/Dictatorship',
        3: 'Thought-terminating cliché',
        4: 'Presenting Irrelevant Data (Red Herring)',
        5: 'Whataboutism',
        6: 'None'}}

id2leaf_label_subtask_2a = {
    'Level 3': {
        1: 'Bandwagon',
        2: 'Appeal to authority',
        3: 'Glittering generalities (Virtue)',
        4: 'Exaggeration/Minimisation',
        5: 'Loaded Language',
        6: 'Flag-waving',
        7: 'Appeal to (Strong) Emotions',
        8: 'Appeal to fear/prejudice',
        9: 'Repetition',
        10: 'Obfuscation, Intentional vagueness, Confusion',
        13: 'Transfer'},
    'Level 4': {
        0: 'Slogans',
        1: 'Bandwagon',
        2: 'Appeal to authority',
        3: 'Flag-waving',
        4: 'Appeal to fear/prejudice',
        5: 'Name calling/Labeling',
        6: 'Doubt',
        7: 'Smears',
        8: 'Reductio ad hitlerum',
        11: 'Whataboutism'},
    'Level 5': {
        0: "Misrepresentation of Someone's Position (Straw Man)",
        1: 'Causal Oversimplification',
        2: 'Black-and-white Fallacy/Dictatorship',
        3: 'Thought-terminating cliché',
        4: 'Presenting Irrelevant Data (Red Herring)',
        5: 'Whataboutism'}}

techniques_to_level_2a = {
    'Persuasion': ['Level 1'],
    'Ethos': ['Level 2'],
    'Pathos': ['Level 2'],
    'Logos': ['Level 2'],
    'Ad Hominem': ['Level 3'],
    'Bandwagon': ['Level 3', 'Level 4'],
    'Appeal to authority': ['Level 3', 'Level 4'],
    'Glittering generalities (Virtue)': ['Level 3'],
    'Exaggeration/Minimisation': ['Level 3'],
    'Loaded Language': ['Level 3'],
    'Flag-waving': ['Level 3', 'Level 4'],
    'Appeal to fear/prejudice': ['Level 3', 'Level 4'],
    'Repetition': ['Level 3'],
    'Obfuscation, Intentional vagueness, Confusion': ['Level 3'],
    'Justification': ['Level 3'],
    'Reasoning': ['Level 3'],
    'Transfer': ['Level 3'],
    'Appeal to (Strong) Emotions': ['Level 3'],
    'Slogans': ['Level 4'],
    'Name calling/Labeling': ['Level 4'],
    'Doubt': ['Level 4'],
    'Smears': ['Level 4'],
    'Reductio ad hitlerum': ['Level 4'],
    'Distraction': ['Level 4'],
    'Simplification': ['Level 4'],
    'Whataboutism': ['Level 4', 'Level 5'],
    "Misrepresentation of Someone's Position (Straw Man)": ['Level 5'],
    'Causal Oversimplification': ['Level 5'],
    'Black-and-white Fallacy/Dictatorship': ['Level 5'],
    'Thought-terminating cliché': ['Level 5'],
    'Presenting Irrelevant Data (Red Herring)': ['Level 5']}
